import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCProvider } from "~/trpc/trpc-react";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCProvider>
          <div className="flex h-full w-full flex-col items-center justify-center">
            <Navbar />
            <div className="container h-full">{children}</div>
          </div>
        </TRPCProvider>
      </body>
    </html>
  );
}
