# download VSCode REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Create a user
POST http://127.0.0.1:3001/api/users
content-type: application/json

{
  "username": "testuser",
  "email": "test@example.com"
}


###
# Create a Google Meet bot (deploy immediately) with default settings
POST http://127.0.0.1:3001/api/bots
content-type: application/json

{
  "userId": 5,
  "meetingTitle": "Test Google Meet",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/orn-ovgv-dym",
    "platform": "google"
  }
}

###
# Create a Google Meet bot with custom settings (overriding some defaults)
POST http://127.0.0.1:3001/api/bots
content-type: application/json

{
  "userId": 1,
  "meetingTitle": "Test Google Meet with Custom Settings",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/mvd-tibd-oxa",
    "platform": "google"
  },
  "botDisplayName": "Custom Bot Name",
  "automaticLeave": {
    "silenceDetection": {
      "timeout": 600000,
      "activateAfter": 120000
    },
    "waitingRoomTimeout": 180000
  }
}

###

# Create an API key
POST http://127.0.0.1:3001/api/api-keys
content-type: application/json

{
  "name": "Test API Key",
  "userId": 5
}

### 

# Get bots
GET http://127.0.0.1:3001/api/bots
content-type: application/json
x-api-key: 1ba6e028b7f9354ace5011bf5406ce61d1da8870644230c69589b45e2dd5f1cc


