# download VSCode REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Create a user
POST http://meetingbot-dev-2081261315.us-east-2.elb.amazonaws.com/api/users
content-type: application/json

{
  "username": "testuser",
  "email": "test@example.com"
}


###
# Create a Google Meet bot (deploy immediately) with default settings
POST http://meetingbot-dev-1753410297.us-east-2.elb.amazonaws.com/api/bots
content-type: application/json

{
  "meetingTitle": "Test Google Meet",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/osn-pemn-piv",
    "platform": "google"
  }
}

###
# Create a Google Meet bot with custom settings (overriding some defaults)
POST http://127.0.0.1:3001/api/bots
content-type: application/json

{
  "meetingTitle": "Test Google Meet with Custom Settings",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/mvd-tibd-oxa",
    "platform": "google"
  },
  "botDisplayName": "Custom Bot Name",
  "automaticLeave": {
    "waitingRoomTimeout": 180000
  }
}

###

# Create an API key
POST http://meetingbot-dev-2081261315.us-east-2.elb.amazonaws.com/api/api-keys
content-type: application/json

{
  "name": "Test API Key"
}

### 

# Get bots
GET http://127.0.0.1:3001/api/bots
content-type: application/json
x-api-key: a4147f16411c5d505ecd31ceeb199976fda87d688aee216339caa5ef313ab621


###

# Create google meet bot local
POST http://127.0.0.1:3001/api/bots
content-type: application/json
x-api-key: 0bc3598273e72800afa66146686c2c5d28cff0aa76f9381b3fd59651e63b4000

{
  "meetingTitle": "Test Meeting",
  "meetingInfo": {
    "meetingId": "86701589057",
    "platform": "zoom",
    "meetingPassword": "6k9dAP"
  }
}

###

# Get bot 53
GET http://127.0.0.1:3001/api/bots/53
content-type: application/json
x-api-key: 0bc3598273e72800afa66146686c2c5d28cff0aa76f9381b3fd59651e63b4000

###me

# Get bot 53 recording
GET http://127.0.0.1:3001/api/bots/53/recording
content-type: application/json
x-api-key: 0bc3598273e72800afa66146686c2c5d28cff0aa76f9381b3fd59651e63b4000



###

# Check Bot Usage
GET http://127.0.0.1:3001/api/usage/day
content-type: application/json
x-api-key: 0bc3598273e72800afa66146686c2c5d28cff0aa76f9381b3fd59651e63b4000