# download VSCode REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://127.0.0.1:8000/create_user
content-type: application/json

{
    "username": "testuser4",
    "email": "testuser4@example.com"
}

###

GET http://127.0.0.1:8000/users
content-type: application/json

###

GET http://127.0.0.1:8000/bots
content-type: application/json

###

POST http://127.0.0.1:8000/create_bot
content-type: application/json

{
    "user_id": 2,
    "meeting_info": {
        "meeting_id": "2",
        "platform": "teams"
    },
    "meeting_name": "Test Meeting",
    "start_time": "2024-01-01T10:00:00Z",
    "end_time": "2024-01-01T11:00:00Z",
    "bot_display_name": "TestBot",
    "bot_image": "http://example.com/bot-image.png",
    "audio_recording_url": "http://example.com/recording.mp3"
}

####

GET http://127.0.0.1:8000/test
content-type: application/json

{
    "name": "John",
    "age": "35"
}